http_password: foobar
ecobee_api_key: foobar
darksky_api_key: foobar
simplisafe_username: foobar
simplisafe_password: foobar
google_client_id: foobar
google_client_secret: foobar
bedroom_apple_tv_login_id: foobar
living_room_apple_tv_login_id: foobar
digital_ocean_api_key: foobar
linode_api_key: foorbar
github_api_key: foobar
lyft_client_id: foobar
lyft_client_secret: footbar
unifi_host: foobar
unifi_username: foobar
unifi_password: foobar
homekit_pincode: '123-45-678'
