http_password: foobar
ecobee_api_key: foobar
darksky_api_key: foobar
simplisafe_username: foobar
simplisafe_password: foobar
bedroom_apple_tv_login_id: foobar
living_room_apple_tv_login_id: foobar
lyft_client_id: foobar
lyft_client_secret: footbar
unifi_host: foobar
unifi_username: foobar
unifi_password: foobar
