http_password: foobar
ecobee_api_key: foobar
darksky_api_key: foobar
simplisafe_username: foobar
simplisafe_password: foobar
google_client_id: foobar
google_client_secret: foobar
bedroom_apple_tv_login_id: foobar
living_room_apple_tv_login_id: foobar
