os: linux
dist: xenial

language: python
python:
  - "3.8.6"
before_install:
  - mkdir -p /ssl
  - touch /ssl/fullchain.pem
  - touch /ssl/privkey.pem
  - cp .secrets-travis.yaml secrets.yaml
install:
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
