homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 36.1880707 
  longitude: -86.7182701
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 355 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Show devices on map
map:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  server_port: 80

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key 

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key 
    monitored_conditions:
      - summary
      - nearest_storm_distance
      - apparent_temperature
      - minutely_summary
      - temperature_max
      - temperature_min
    update_interval:
      minutes: 5

  - platform: gtfs
    origin: PRECARSN
    destination: MCC4_14
    data: google_transit.zip

  - platform: gtfs
    origin: WES25AEN
    destination: MCC5_5
    data: google_transit.zip

# Text to speech
tts:
  - platform: google

# Alarm
alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username 
  password: !secret simplisafe_password 

# Webcam
camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.100:8081

# iOS Notifications
ios:

zone:
  - name: Vanderbilt
    latitude: 36.145793
    longitude: -86.8096052
    icon: mdi:briefcase

  - name: Emma
    latitude: 36.15788
    longitude: -86.7675063
    icon: mdi:briefcase

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
