homeassistant:
  # Customization files
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# SSL
http:
  base_url: https://hassio.yearg.in
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Monitor system health
system_health:

# Enable AppleTV devices
apple_tv:
  - host: 10.251.0.107
    login_id: !secret living_room_apple_tv_login_id
    name: Living Room Apple TV
    start_off: true
    credentials: !secret living_room_apple_tv_credentials

  - host: 10.251.0.108
    login_id: !secret bedroom_apple_tv_login_id
    name: Bedroom Apple TV
    start_off: true

homekit:
  filter:
    include_domains:
      - alarm_control_panel

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

# Show devices on map
map:

# Mobile App Enabled
mobile_app:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Time and Date
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key 

# Speedtest.net
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# Included Files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
logger: !include logger.yaml
