homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 36.1880707 
  longitude: -86.7182701
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 355 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Enable AppleTV devices
apple_tv:
  - host: 192.168.1.71
    login_id: !secret bedroom_apple_tv_login_id
    name: Bedroom Apple TV
    start_off: true

  - host: 192.168.1.67
    login_id: !secret living_room_apple_tv_login_id
    name: Living Room Apple TV
    start_off: true

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Show devices on map
map:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  server_port: 80

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key 

# Wink (for switches)
wink:

sensor:
  # Weather
  - platform: darksky
    api_key: !secret darksky_api_key 
    monitored_conditions:
      - minutely_summary
      - nearest_storm_distance
      - temperature
      - temperature_max
      - temperature_min
    update_interval:
      minutes: 5

  # Bus Schedules
  - platform: gtfs
    name: "Next #4 Bus"
    origin: PRECARSN
    destination: MCC4_14
    data: google_transit.zip

  - platform: gtfs
    name: "Next #3/#5 Bus"
    origin: WES25AEN
    destination: MCC5_5
    data: google_transit.zip

  # Lyft
  - platform: lyft
    client_id: !secret lyft_client_id
    client_secret: !secret lyft_client_secret
    start_latitude: 36.1880707
    start_longitude: -86.7182701
    end_latitude: 36.1610221
    end_longitude: -86.7815272

  # Whois
  - platform: whois
    domain: myseatshare.com
    name: myseatshare.com

  - platform: whois
    domain: samantha-y.com
    name: samantha-y.com

  - platform: whois
    domain: samanthay.com
    name: samanthay.com

  - platform: whois
    domain: seatsha.re
    name: seatsha.re

  - platform: whois
    domain: slyeargin.com
    name: slyeargin.com

  - platform: whois
    domain: stephenyeargin.com
    name: stephenyeargin.com

  - platform: whois
    domain: strangepursuit.net
    name: strangepursuit.net

  - platform: whois
    domain: unanimous.ly
    name: unanimous.ly

  - platform: whois
    domain: yearg.in
    name: yearg.in

  - platform: whois
    domain: yourliberalfriends.com
    name: yourliberalfriends.com

  # TravisCI
  - platform: travisci
    api_key: !secret github_api_key

  # SpeedTest
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

# Alarm
alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username 
  password: !secret simplisafe_password 

# Webcam
camera:
  - platform: mjpeg
    name: Den
    mjpeg_url: http://192.168.1.100:8081

  - platform: mjpeg
    name: Office
    mjpeg_url: http://192.168.1.85:80

# iOS Notifications
ios:

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Digital Ocean
digital_ocean:
  access_token: !secret digital_ocean_api_key

# Linode
linode:
  access_token: !secret linode_api_key

# Binary Sensors
binary_sensor:
  - platform: linode
    nodes:
      - 'yeargin'

# Zones
zone:
  - name: Vanderbilt
    latitude: 36.145793
    longitude: -86.8096052
    icon: mdi:briefcase

  - name: Emma
    latitude: 36.15788
    longitude: -86.7675063
    icon: mdi:briefcase

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
