homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 36.1880707 
  longitude: -86.7182701
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 153
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization files
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Enable AppleTV devices
apple_tv:
  - host: 10.252.0.107
    login_id: !secret living_room_apple_tv_login_id
    name: Living Room Apple TV
    start_off: true

  - host: 10.252.0.108
    login_id: !secret bedroom_apple_tv_login_id
    name: Bedroom Apple TV
    start_off: true

homekit:
  filter:
    include_entities:
      - alarm_control_panel.simplisafe

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

# Show devices on map
map:

http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret http_base_url
  # server_port: 8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key 

# Wink (for switches)
wink:

sensor:
  # Weather
  - platform: darksky
    api_key: !secret darksky_api_key 
    monitored_conditions:
      - minutely_summary
      - hourly_summary
      - nearest_storm_distance
      - temperature
      - temperature_high
      - temperature_low
    update_interval:
      minutes: 5

  - platform: pollen
    zip_code: "37206"
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - disease_average_forecasted

  # SpeedTest
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

# Alarm
simplisafe:
  accounts:
    - username: !secret simplisafe_username 
      password: !secret simplisafe_password 

# Webcam
camera:
  - platform: mjpeg
    name: Den
    mjpeg_url: http://10.252.0.100:8081

  - platform: mjpeg
    name: Office
    mjpeg_url: http://10.252.0.109:80

# iOS Notifications
ios:

# Unifi Tracking
device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

# Zones
zone:
  - name: Home
    latitude: 36.1880707 
    longitude: -86.7182701
    radius: 150
    icon: mdi:home

  - name: Vanderbilt
    latitude: 36.146122
    longitude: -86.808906
    radius: 150
    icon: mdi:briefcase

  - name: Campaign Monitor
    latitude: 36.15788
    longitude: -86.7675063
    radius: 150
    icon: mdi:briefcase

# Included Files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
logger: !include logger.yaml
